### ISSUE TITLE
Bug affichage profil

### ISSUE THREAD

**Issue by twi-zi** [PiloteCode/PiloteShopping#16]
- Aller dans le profil utilisateur (https://piloteshopping.com/dashboard.php#)

Si le compte a était créé sans numéro de téléphone ( qui est facultatif dans l'inscription) le profil avec l'image le nom  d'utilisateur, l'email, et le numéro de téléphone ne s'affiche pas et affiche a la place un message d'erreur

Le numéro de téléphone étant facultatif le reste des informations devrai quand même s'afficher 

A vérifier car je ne suis pas sur que cela Vien de la car je ne peut retirer mon numéro de téléphone pour tester

**Comment by PiloteCode** [comment]
Il est possible d'avoir une capture d'écran?

**Comment by twi-zi** [comment]
Non le problème s'étant résolu car j'ai mit un numéro, je n'est plus le bug d'affichage néanmoins je peux vous montrer la partie qui s'afficher pas ![Screenshot_2024-08-16-20-48-17-59_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/user-attachments/assets/70fa6653-61f1-4d93-8e8d-b297b9443ff8)

**Comment by PiloteCode** [comment]
Ah ouais le screen de bz

**Comment by PiloteCode** [comment]
Corrigé.
